language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy
  - pip install pandas
  - pip install sklearn
# command to run tests
script: 
  - python sourcepredict -r canis_familiaris ./data/test/dog_test_sample.csv
