language: python
python:
  - "3.6"
install:
  - sudo apt-get update
script: 
  - python setup.py install
  - sourcepredict -s data/test/training/test_sources.csv -l data/test/training/test_labels.csv data/test/testing/test_data.csv
  - pytest --cov sourcepredictlib  tests
after_success:
  - coveralls

