{% set version = "0.5" %}

package:
  name: sourcepredict
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/maxibor/sourcepredict.git

requirements:
  run:
    - python 3.6.*
    - numpy >=1.16.4
    - pandas >=0.24.1
    - scikit-learn >=0.20.1
    - scikit-bio >=0.5.5
    - umap-learn >=0.3.7
    - scipy >=1.1.0
    - ete3 >=3.1.1
    
test:
  source_files:
    - data
  commands:
    - sourcepredict --help

about:
  home: https://github.com/maxibor/sourcepredict
  license: GPL-3.0
  summary: 'Prediction/source tracking of sample source using composite learning'

# Build using: conda build .
