package:
  name: sourcepredict
  version: "0.34"

source:
  git_rev: 0.34
  git_url: https://github.com/maxibor/sourcepredict.git

requirements:
  run:
    - python 3.6.*
    - numpy
    - pandas
    - scikit-learn
    - scikit-bio
    - umap-learn
    - ete3

test:
  source_files:
    - data
  commands:
    - sourcepredict --help

about:
  home: https://github.com/maxibor/sourcepredict
  license: GPL-3.0
  summary: 'Prediction/source tracking of sample source using composite learning'

# Build using: conda build -c conda-forge -c etetoolkit -c bioconda .
